### ISSUE TITLE
Use AsciiDoctor parse instead of Cli

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma#3]
Currently we hook AsciiDoctor at the `Cli` level, but we should directly use the AsciiDoctor parse routine instead. i.e. we should not depend on AsciiDoctor for CLI parsing and options.

Now:
```ruby
asciidoc_options = Asciidoctor::Cli::Options.new(
  backend: options[:type],
  header_footer: true
)

if asciidoc_options.parse!([options[:filename]]) == 0
...

invoker = Asciidoctor::Cli::Invoker.new asciidoc_options
GC.start
invoker.invoke!
exit invoker.code

```

**Comment by opoudjis** [comment]
Why?

Yes, I know that I'm being difficult, but I want to understand what dependencies are being considered harmful here.

**Comment by ronaldtse** [comment]
Because we want to switch it out with Selagraph in the future?

**Comment by opoudjis** [comment]
But the Cli does not prevent that, and it's going to make it easier to deal with command line invocation of the asciidoctor.

If you want Selagraph in the future, you're going to be specifying a document source option for the script as well as a target standard option (or else have the script infer it from the document contents). In fact, the script already allows that, although it only accepts asciidoc as a format.

So if the document is in asciidoc, it will invoke asciidoc, and cli vs parser makes no difference. If the document is in selagraph, the script invokes selagraph; if markdown, it invokes markdown. Selagraph is not going to do anything with asciidoc source anyway; so how the asciidoc is processed, parser or cli, is irrelevant.

Or am I missing something?

**Comment by ronaldtse** [comment]
You have a point. However, `Cli` is an internal Asciidoctor API, vs the actual backend `parse` operation is a public API. To me instead of trying to fake CLI options and fake invoke, might as well we just call `parse` on the Asciidoctor backend.

The other reason is -- I know you hate this -- refactoring -- the input and output. Metanorma should handle:
1. Read input and give to input processor
2. Input processor creates some subclass of a StandardDocument model
3. Pass the StandardDocument model instance to an (one or more) output processor

Today, all of 1, 2, 3 are handled by the `asciidoctor-blah` gems. But only 2 should be handled by it.

**Comment by opoudjis** [comment]
The convert_file command can operate from an input string instead of from a file.

We don't actually want this though, because we need the filename for the naming of isodoc outputs. However, we do need to manipulate asciidoctor content (for https://github.com/riboseinc/asciidoctor-iso/issues/133).  So we will likely end up passing the file name as an argument into isodoc.

**Comment by ronaldtse** [comment]
@opoudjis I think we can actually pass the document attributes separately from the Asciidoc content string itself; Asciidoctor allows setting metadata (as a hash) separately from the content. So we can set the defaults outside of the string content (which is read from the file).

We should handle the filename of input / output files separately from Asciidoctor.

**Comment by opoudjis** [comment]
The standards other than RFC2/3 now invoke Asciidoctor separately from Isodoc, and invoke Asciidoctor with a string rather than a file. Document attributes are extracted from the Asciidoctor string, without parsing the document, and passed on to Isodoc. The filename is passed to Isodoc.

The RFC2/3 standard is invoked as a file, and until there is a mapping from RFC XML to ISOXML, I strongly suggest we leave it be.

I've also unearthed in the process that the validation of RFC XML requires a local instance of rfc2629.dtd, and we can't keep compiling RFC XML in a fixed directory where rfc2629.dtd is already there. (And configuring validators to find DTD files somewhere else is horrid.) The asciidoctor-rfc gem now outputs rfc2629.dtd to the local directory before running validation.
